name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.1, 8.0, 7.4, 7.3]
        laravel: [8.*, 9.*]
        stability: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        exclude:
          - laravel: 9.*
            php: 7.4
          - laravel: 9.*
            php: 7.3

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require "illuminate/contracts:${{ matrix.laravel }}" --dev --no-interaction --no-update
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
